const GET_CHARACTERS = 'GET_CHARACTERS';
const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';

export { GET_CHARACTERS, GET_CHARACTERS_SUCCESS, GET_CHARACTERS_ERROR };
